In [ ]:
import torch
print(torch.__version__)

2.1.0+cu121


In [ ]:
x = torch.tensor([1, 2, 3])
print(x)

tensor([1, 2, 3])


In [ ]:
y = x + 5
print(y)

tensor([6, 7, 8])


In [ ]:
z = x.view(3, 1)
print(z)

tensor([[1],
        [2],
        [3]])


In [ ]:
x = torch.tensor([1., 2., 3.], requires_grad=True)
y = torch.tensor([4., 5., 6.], requires_grad=True)
z = x * y
print(z)

tensor([ 4., 10., 18.], grad_fn=<MulBackward0>)


In [ ]:
z.backward(torch.tensor([1., 1., 1.]))
print(x.grad)
print(y.grad)

tensor([4., 5., 6.])
tensor([1., 2., 3.])


# **Building the basic NN**

In [ ]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

In [ ]:
class SimpleNet(nn.Module):
    def __init__(self):
        super(SimpleNet, self).__init__()

        self.fc1 = nn.Linear(3, 3)
        self.fc2 = nn.Linear(3, 2)
        self.fc3 = nn.Linear(2, 1)

    def forward(self, x):

        x = F.relu(self.fc1(x))
        x = F.relu(self.fc2(x))
        x = self.fc3(x)

        return x

net = SimpleNet()
print(net)
print(net(x))
print(x.shape)
print(net(y))
print(y)

SimpleNet(
  (fc1): Linear(in_features=3, out_features=3, bias=True)
  (fc2): Linear(in_features=3, out_features=2, bias=True)
  (fc3): Linear(in_features=2, out_features=1, bias=True)
)
tensor([-0.0759], grad_fn=<ViewBackward0>)
torch.Size([3])
tensor([-0.0759], grad_fn=<ViewBackward0>)
tensor([4., 5., 6.], requires_grad=True)


In [ ]:
criterion = nn.MSELoss()
optimizer = optim.SGD(net.parameters(), lr = 0.01)



inputs = torch.randn(1,3)
print("Shape of the Inputs : ", inputs.shape)
print("Input Data : ", inputs)
targets = torch.randn(1,1)
print("Shape of the Targets : ", targets.shape)

outputs = net(inputs)
loss = criterion(outputs, targets)

print("Loss : ", loss)

optimizer.zero_grad()
loss.backward()
optimizer.step()

Shape of the Inputs :  torch.Size([1, 3])
Input Data :  tensor([[-0.9527, -0.4139, -0.1961]])
Shape of the Targets :  torch.Size([1, 1])
Loss :  tensor(0.0979, grad_fn=<MseLossBackward0>)


In [ ]:
num_epochs = 50

for epoch in range(num_epochs):


    outputs = net(inputs)
    loss = criterion(outputs, targets)

    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

    print("Epoch : ", epoch, " Loss : ", loss.item())

Epoch :  0  Loss :  0.052383892238140106
Epoch :  1  Loss :  0.05030948668718338
Epoch :  2  Loss :  0.04831722751259804
Epoch :  3  Loss :  0.046403881162405014
Epoch :  4  Loss :  0.04456627368927002
Epoch :  5  Loss :  0.04280144348740578
Epoch :  6  Loss :  0.041106484830379486
Epoch :  7  Loss :  0.03947868570685387
Epoch :  8  Loss :  0.03791533410549164
Epoch :  9  Loss :  0.036413900554180145
Epoch :  10  Loss :  0.03497191146016121
Epoch :  11  Loss :  0.0335870124399662
Epoch :  12  Loss :  0.032256972044706345
Epoch :  13  Loss :  0.030979609116911888
Epoch :  14  Loss :  0.02975280024111271
Epoch :  15  Loss :  0.028574589639902115
Epoch :  16  Loss :  0.027443045750260353
Epoch :  17  Loss :  0.026356302201747894
Epoch :  18  Loss :  0.025312600657343864
Epoch :  19  Loss :  0.024310236796736717
Epoch :  20  Loss :  0.023347537964582443
Epoch :  21  Loss :  0.022422989830374718
Epoch :  22  Loss :  0.021535029634833336
Epoch :  23  Loss :  0.02068225108087063
Epoch :  24  

In [ ]:
for name, param in net.named_parameters():
  print(name, param.size())
  print(param)

fc1.weight torch.Size([3, 3])
Parameter containing:
tensor([[-0.0746,  0.2847, -0.5018],
        [-0.3122,  0.0963,  0.4010],
        [ 0.2448, -0.0253,  0.5576]], requires_grad=True)
fc1.bias torch.Size([3])
Parameter containing:
tensor([ 0.3520, -0.0636,  0.1937], requires_grad=True)
fc2.weight torch.Size([2, 3])
Parameter containing:
tensor([[-0.4812,  0.0066, -0.3202],
        [ 0.2105, -0.3958, -0.4867]], requires_grad=True)
fc2.bias torch.Size([2])
Parameter containing:
tensor([ 0.1862, -0.0551], requires_grad=True)
fc3.weight torch.Size([1, 2])
Parameter containing:
tensor([[-0.6404,  0.0480]], requires_grad=True)
fc3.bias torch.Size([1])
Parameter containing:
tensor([1.4845], requires_grad=True)
